# Change these first  ... https://upptime.js.org/docs/configuration/
owner:  Xiija
repo:   UpMonitor

# Add your sites here
sites:
  - name: Bolo
    url: https://Bolo.xiija.repl.co
  - name: Dr.Klahn
    url: https://Dr-Klahn--xiija.repl.co
  # - name: Google
  #   url: https://www.google.com
  #   icon: https://www.google.com/favicon.ico   
 

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /UpMonitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: UpMonitor Status Home
  introTitle: "**UpMonitor Status Page**"
  introMessage:  A Monitor for Xiija's bots <br> [**Get your own for free**](https://upptime.js.org/docs/get-started)
  navbar:
    - title: Matrix Screensaver
      href: https://xiija.github.io/MAIN/Matrix1-1-4/index.html
    - title: UpMonitor Github Repo
      href: https://github.com/Xiija/UpMonitor

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

# user-agent: your-github-username
